# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: s3-backup add-on
version: "0.0.1"
slug: example
description: Example add-on
url: "https://github.com/geraldhansen/homeassistant-addons/tree/main/s3-backup"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "s3-backup ..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-addon-s3-backup"
